### ISSUE TITLE
Future improvements

### ISSUE THREAD

**Issue by dieghernan** [rOpenSpain/mapSpain#30]
# Notes

`cartography` is officially on maintenance mode. Consider the migration to another package, as `tmap`.

# Roadmap

- [x] Add vignette on CRAN
- [x] Move plots to `tmap`
- [ ] Refactor test files - possible running some test only on releases, via version assessment `home <- length(unclass(packageVersion("PKGNAME"))[[1]]) == 4`

**Comment by dieghernan** [comment]
Included on v0.2.2

**Comment by dieghernan** [comment]
#35
